version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "type:deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "type:deps"
      - "type:ci"
